# flake8: noqa
"""empty message

Revision ID: 15baa4cc0d8
Revises: 39dac198d3a
Create Date: 2015-06-21 19:25:59.606323

"""

# revision identifiers, used by Alembic.
revision = '15baa4cc0d8'
down_revision = '39dac198d3a'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('is_primary', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest', 'is_primary')
    ### end Alembic commands ###
