# flake8: noqa
"""empty message

Revision ID: 1cc45bbe916
Revises: 377d618daee
Create Date: 2015-04-08 11:10:52.789416

"""

# revision identifiers, used by Alembic.
revision = '1cc45bbe916'
down_revision = '377d618daee'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvp', sa.Column('guest_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rsvp', 'guest', ['guest_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rsvp', type_='foreignkey')
    op.drop_column('rsvp', 'guest_id')
    ### end Alembic commands ###
