# flake8: noqa
"""empty message

Revision ID: 1fe3a933ff0
Revises: 55b2cc23fc7
Create Date: 2015-03-26 17:17:39.735523

"""

# revision identifiers, used by Alembic.
revision = '1fe3a933ff0'
down_revision = '55b2cc23fc7'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('invite_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guest', 'invite', ['invite_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guest', type_='foreignkey')
    op.drop_column('guest', 'invite_id')
    ### end Alembic commands ###
