# flake8: noqa
"""empty message

Revision ID: 202e70f30e8
Revises: 31f4f75bbcd
Create Date: 2015-06-06 20:43:24.011607

"""

# revision identifiers, used by Alembic.
revision = '202e70f30e8'
down_revision = '31f4f75bbcd'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest', sa.Column('is_child', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest', 'is_child')
    ### end Alembic commands ###
