# flake8: noqa
"""empty message

Revision ID: 20327cc8bc
Revises: 1fe3a933ff0
Create Date: 2015-03-30 12:27:57.392110

"""

# revision identifiers, used by Alembic.
revision = '20327cc8bc'
down_revision = '1fe3a933ff0'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'firstname', new_column_name='first_name')
    op.alter_column('guest', 'lastname', new_column_name='last_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guest', 'first_name', new_column_name='firstname')
    op.alter_column('guest', 'last_name', new_column_name='lastname')
    ### end Alembic commands ###
