# flake8: noqa
"""empty message

Revision ID: 377d618daee
Revises: 20327cc8bc
Create Date: 2015-04-02 10:24:28.643193

"""

# revision identifiers, used by Alembic.
revision = '377d618daee'
down_revision = '20327cc8bc'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvp')
    ### end Alembic commands ###
