# flake8: noqa
"""empty message

Revision ID: 39dac198d3a
Revises: 53b14b15713
Create Date: 2015-06-12 19:04:33.414234

"""

# revision identifiers, used by Alembic.
revision = '39dac198d3a'
down_revision = '53b14b15713'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('has_room', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite', 'has_room')
    ### end Alembic commands ###
