# flake8: noqa
"""empty message

Revision ID: 53b14b15713
Revises: 202e70f30e8
Create Date: 2015-06-12 15:46:53.547068

"""

# revision identifiers, used by Alembic.
revision = '53b14b15713'
down_revision = '202e70f30e8'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rsvp', sa.Column('name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rsvp', 'name')
    ### end Alembic commands ###
