# flake8: noqa
"""empty message

Revision ID: 55b2cc23fc7
Revises: 4b688e9382
Create Date: 2015-03-26 15:00:07.886638

"""

# revision identifiers, used by Alembic.
revision = '55b2cc23fc7'
down_revision = '4b688e9382'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('token', sa.String(), nullable=True))
    op.drop_column('invite', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invite', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('invite', 'token')
    ### end Alembic commands ###
