# flake8: noqa
"""empty message

Revision ID: 5a915ebfc5a
Revises: 1cc45bbe916
Create Date: 2015-04-08 21:37:29.646311

"""

# revision identifiers, used by Alembic.
revision = '5a915ebfc5a'
down_revision = '1cc45bbe916'


from alembic import op
import sqlalchemy as sa



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
